name: feature_settings
description: Settings feature

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: 0.2.0

  edu_core:
    path: ../../edu_core
  edu_services:
    path: ../../edu_services

  equatable: 2.0.5
  flutter_bloc: 8.1.1

dev_dependencies:
  dependency_validator: 3.2.2
  lint_rules:
    path: ../../lint_rules