name: feature_registration
description: Registration feature

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: 0.2.0

  edu_core:
    path: ../../edu_core
  edu_repositories:
    path: ../../edu_repositories

  equatable: 2.0.5
  flutter_bloc: 8.1.1
  formz: 0.4.1
  json_annotation: 4.8.0

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  json_serializable: 6.6.1
  lint_rules:
    path: ../../lint_rules