name: edu_core
description: Educore

publish_to: 'none'

version: 0.0.1

dependencies:
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  open_mail_app: 0.4.5

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  dependency_validator: 3.2.2
  lint_rules:
    path: ../lint_rules