name: edu_core
description: Educore

publish_to: 'none'

version: 0.0.1

dependencies:
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_email_sender: 5.1.0
  intl: 0.17.0
  open_mail_app: 0.4.5

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  dependency_validator: 3.2.2
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1