name: feature_models_list_provider
description: Models list provider feature

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc_concurrency: 0.2.0

  edu_core:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_core
      ref: v0.0.1
  edu_models:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_models
      ref: v0.0.1
  edu_repositories:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_repositories
      ref: v0.0.1

  equatable: 2.0.5
  flutter_bloc: 8.1.1

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  json_serializable: 6.6.1
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1