name: edu_ui_components
description: EduUI components

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  edu_core:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_core
      ref: v0.0.1
  edu_localizations:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_localizations
      ref: v0.0.1
  edu_models:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_models
      ref: v0.0.1

  equatable: 2.0.5
  extended_image: 8.0.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_staggered_grid_view: 0.6.2
  freezed_annotation: 2.2.0
  intl: 0.18.0
  keyboard_utils: 1.3.4
  pin_code_fields: 7.4.0
  shimmer: 2.0.0

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  freezed: 2.3.2
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/errors/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: lib/assets/fonts/CustomIcons/CustomIcons.ttf
    - family: Rubik
      fonts:
        - asset: lib/assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Rubik/Rubik-BlackItalic.ttf
          style: italic
          weight: 900

        - asset: lib/assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: lib/assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Rubik/Rubik-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: lib/assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: lib/assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Rubik/Rubik-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: lib/assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
          weight: 400

        - asset: lib/assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Rubik/Rubik-LightItalic.ttf
          style: italic
          weight: 300