name: edu_repositories
description: Edurepositories. All shared repositories

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  edu_core:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_core
      ref: v0.0.1
  edu_services:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_services
      ref: v0.0.1

  json_annotation: 4.8.0

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  json_serializable: 6.6.1
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1