name: edu_repositories
description: Edurepositories. All shared repositories

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  edu_core:
    path: ../edu_core
  edu_services:
    path: ../edu_services

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  json_serializable: 6.6.1
  lint_rules:
    path: ../lint_rules